# Code style configuration
# https://prettier.io/docs/en/options.html

printWidth: 120
trailingComma: all
useTabs: false
tabWidth: 2
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
jsxBracketSameLine: true
bracketSpacing: true
arrowParens: always
htmlWhitespaceSensitivity: strict
endOfLine: auto