import { ScrapedSong } from './song.interface';

export const mockSongs: ScrapedSong[] = [
  {
    id: '04cd7884-cab4-4d9f-ad4e-e55fad3c7dcc',
    song: {
      artist_names: 'Young Thug (Ft. Casino)',
      full_title: 'Untitled (Casino x Thug) by Young Thug (Ft. Casino)',
      header_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      id: 0,
      uuid: '9127537',
      path: '/Young-thug-untitled-casino-x-thug-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      title: 'Untitled (Casino x Thug)',
      url: 'https://genius.com/Young-thug-untitled-casino-x-thug-lyrics',
    },
    lyrics: [
      'Whole crew ___, free Roscoe, YSL',
      "Two-thousand dollar T-shirt and it's messy",
      '(ATL Jacob)',
      "Think it's by Ye",
      'Brrr (Yeah), big bird',
      'Reebok, pink hot',
      'Easy check, ham hock',
      'Cauliflower diamonds',
      'Twelve colors, 6ix9ine',
      'Peacock diamonds',
      'Twelve colors, T-top',
      'Fat butt, D cups',
      'She got on white diamonds, Klu Klux',
      'Reebok, pink hot',
      'Easy check, ham hock',
      'Cauliflower diamonds',
      'Twelve colors, 6ix9ine',
      'Peacock diamonds',
      'Twelve colors, T-top',
      'Fat butt, D cups',
      'She got on white diamonds, Klu Klux',
      'Open Instrumental',
      'Reebok, pink hot',
      'Easy check, ham hock',
      'Cauliflower diamonds',
      'Twelve colors, 6ix9ine',
      'Peacock diamonds',
      'Twelve colors, T-top',
      'Fat butt, D cups',
      'She got on white diamonds, Klu Klux, okay',
    ],
  },
  {
    id: 'edbbb392-aeae-4a1f-b3a0-29b5adab4407',
    song: {
      artist_names: 'YoungBoy Never Broke Again (Ft. Gunna \u0026 Young Thug)',
      full_title: 'All My Hoes by YoungBoy Never Broke Again (Ft. Gunna \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.640x640x1.jpg',
      id: 0,
      uuid: '5854133',
      path: '/Youngboy-never-broke-again-all-my-hoes-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.640x640x1.jpg',
      title: 'All My Hoes',
      url: 'https://genius.com/Youngboy-never-broke-again-all-my-hoes-lyrics',
    },
    lyrics: [
      "I'll put a Patek Philippe on your head (Ayy)",
      'I got twenty bitches in my jet, dog (In my bed, dog)',
      "I'm missing molly with my med (Yeah)",
      'Put a couple extras in my red (Woo)',
      'Come and kill everything but the kids (Woo)',
      'Bring me the head and everything else get rid (Woo)',
      "Gold on my teeth, the reason I smile, I'm never kiddin' (Woah)",
      "'Bout to pull up on your block, hop out my car, get in your shit (Yeah)",
      'My mama told you I was a star (My mama told you)',
      "I bought my mansion accordin' to my calls (Yeah)",
      '___ been with me ever since this morning',
      "We just rippin' around this bitch, we ain't doin' nothin' but stuntin' (Turn up)",
      'Got big baguettes in every single one of my chains (Every single one), ayy',
      "Spend a big ol' check on every single one of my mains (Uh, facts)",
      "I tried to tell you it's no cap inside my game, no (No cap inside my game)",
      "I'm swervin' the whole street, ain't got no lane, no (Skrrt, skrrt)",
    ],
  },
  {
    id: '30b3e78c-13dc-47a3-bbf4-788bfafdcb01',
    song: {
      artist_names: 'Young Stoner Life \u0026 Young Thug (Ft. Lil Keed)',
      full_title: 'Goin Up by Young Stoner Life \u0026 Young Thug (Ft. Lil Keed)',
      header_image_thumbnail_url: 'https://images.genius.com/7c12093f3439ce524517e302a3f69ae1.300x169x1.jpg',
      header_image_url: 'https://images.genius.com/7c12093f3439ce524517e302a3f69ae1.1000x563x1.jpg',
      id: 0,
      uuid: '3902324',
      path: '/Young-stoner-life-and-young-thug-goin-up-lyrics',
      release_date_for_display: 'August 17, 2018',
      song_art_image_thumbnail_url: 'https://images.genius.com/0eabaa82bc43e66ab0d5b2b38c42b321.300x300x1.png',
      song_art_image_url: 'https://images.genius.com/0eabaa82bc43e66ab0d5b2b38c42b321.1000x1000x1.png',
      title: 'Goin Up',
      url: 'https://genius.com/Young-stoner-life-and-young-thug-goin-up-lyrics',
    },
    lyrics: [
      'Yeah',
      '(Khaliel)',
      'Do you love me, baby?',
      'Like I love you, baby?',
      'Keed, yeah',
      "Yeah, in that Bentley coupe doin' the whole thing",
      'Throw that shit up to the roof, bitch, we balling',
      'Bring them bitches in the room if they all in',
      "I spent so many racks on these pants, bitch, I'm stylin' (Yeah, yeah)",
      "Bitch, I'm goin' up, bitches goin' down on me (Yeah)",
      "Bitch, I'm slowed up, I been drinkin' codeine (I been drinkin' codeine)",
      "So much blue cheese in these pants, look like the money huggin' me",
      'And when I hop off in the crowd they hold me way, way up',
      'I keep some bread in my pocket, Jimmy Dean (Yeah)',
      'I add a rose gold chain when I drink my lean (Act)',
      "I add Chanel on the rip of shawty's jeans (Slatt)",
      'I need a Tylenol, I done popped too many beans (Woo)',
      "I'm at the VMA awards and I'm bringin' her out (Yeah)",
      'I left the dentist with some braces in her mouth (Tighten it up)',
      'I told your darling, "Shawty was on South" (Yeah)',
      "I take this 'Rari, park it at the house (Skrrt)",
      'I told her to stop it (Woo)',
      'Call me and take these up (These up)',
      'I told her to stop it (Buh, buh, buh, buh)',
      'I got on my knees, oh (Stop it)',
      'I bought you this Rollie',
      "You know it came forty-four B'd up (Forty-four), yeah",
      'Cupid fishbowl is at the top (Woo)',
      'I put the tint on it (Yeah)',
      'She tryna sit on it (Yeah)',
      'I can throw the climax (What?)',
      'I got the bill on it, yeah',
      'It came in wireless (And what?)',
      "I spent a mill' on it, yeah",
      "I'm smokin' on thrax pack (*Cough*)",
      "Gotta keep the seal on it, yeah (That's kush)",
      'You catch a body (Brrat)',
      'Gotta put appeal on it, yeah (Ah, boom)',
      "I'm Prince Hakeem (What?)",
      'Straight out the trenches with it, yeah (Ah)',
      "I'm Bob Marley (Bob)",
      'The next century, yeah (Yeah)',
      'Hopped in with your boo (Woo)',
      "I wanna see chest up and then nothin' else",
      "Yeah, in that Bentley coupe doin' the whole thing",
      'Throw that shit up to the roof, bitch, we balling',
      'Bring them bitches in the room if they all in',
      "I spent so many racks on these pants, bitch, I'm stylin' (Yeah, yeah)",
      "Bitch, I'm goin' up, bitches goin' down on me (Yeah)",
      "Bitch, I'm slowed up, I been drinkin' codeine (I been drinkin' codeine)",
      "So much blue cheese in these pants, look like the money huggin' me",
      'And when I hop off in the crowd they hold me way, way up (I keep some)',
      "Yeah, in that Bentley coupe doin' the whole thing (Slatt, huh, slime ball)",
      'Throw that shit up to the roof, bitch, we balling',
      'Bring them bitches in the room if they all in',
      "I spent so many racks on these pants, bitch, I'm stylin' (Yeah, yeah)",
      "Bitch, I'm goin' up, bitches goin' down on me (Yeah)",
      "Bitch, I'm slowed up, I been drinkin' codeine (I been drinkin' codeine)",
      "So much blue cheese in these pants, look like the money huggin' me",
      'And when I hop off in the crowd they hold me way, way up (I keep some)',
      "Bitch, I'm goin' up (Do you love me, baby?)",
      "Bitch, I'm slowed up (Like I love you, baby?)",
      "Bitch, I'm goin' up (Do you love me, baby?)",
      "Bitches goin' down me",
      "Bitch, I'm slowed up",
      "I been drinkin' codeine (Like I love you, baby? Yeah)",
      'Do you love me, baby?',
      'Like I love you, baby?',
      'Do you love me, baby?',
      'Like I love you, baby? Yeah',
    ],
  },
  {
    id: 'ca261b28-fe2b-4910-bb18-ecef409f52dc',
    song: {
      artist_names: 'Young Stoner Life \u0026 Young Thug (Ft. Jacquees \u0026 Trapboy Freddy)',
      full_title: 'January 1st by Young Stoner Life \u0026 Young Thug (Ft. Jacquees \u0026 Trapboy Freddy)',
      header_image_thumbnail_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.1000x1000x1.jpg',
      id: 0,
      uuid: '3902325',
      path: '/Young-stoner-life-and-young-thug-january-1st-lyrics',
      release_date_for_display: 'August 17, 2018',
      song_art_image_thumbnail_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.1000x1000x1.jpg',
      title: 'January 1st',
      url: 'https://genius.com/Young-stoner-life-and-young-thug-january-1st-lyrics',
    },
    lyrics: [
      '(DY Krazy)',
      'I got diamonds on my toes',
      'Way up on my nose',
      '(Wheezy outta here)',
      'You know how I go, yeah',
      "I'm fresh as fuck, I told that bitch I should've came in a hearse (Woo)",
      'I put Chanel on her ears and on her neck and her purse (Yeah)',
      "I'm number one, my birthday should've been January the first, woah",
      'Oh (Yeah, yeah, yeah)',
      'I got diamonds from my toes up to my top',
      "I got pink toes runnin' 'round the house",
      'I thank God I understand the way it go (I understand)',
      'She a damn crew hopper, XO, yeah (Yeah, yeah)',
      'I got diamonds on my toes, motherfucker',
      'I got diamonds in my nose, yeah (I got diamonds in my nose)',
      "I been rockin' Kenneth Cole, motherfucker (Rockin' Cole)",
      'My bitch is clean as Pine-Sol, motherfucker, yeah (Woo)',
      'Pop a school bus, bitches tryna screw us (Yeah)',
      "Fuck you old school niggas, ain't no schoolin' us",
      "I let my son whip a Ferrari like it's Toys-R-Us (Rrt)",
      "I rock Hermès, I'm designered up ('Signered up)",
      "Can't get rid of us",
      'I gotta hitters, drug dealers, good bitches (Yeah)',
      "I got bitches goin' brazy, no Ritalin (Yeah)",
      "I get money and that's shady, for real, bruh",
      'You can\'t say, "Bruh, I done this shit"',
      '(Wheezy outta here) Woo',
      "I'm fresh as fuck, I told that bitch I should've came in a hearse (Should've came in a hearse)",
      'I put Chanel on her ears and on her neck and her purse (Chanel)',
      "I'm number one, my birthday should've been January the first, woah (Woo, January the first)",
      'Oh (Yeah, yeah, yeah)',
      'I got diamonds from my toes up to my top',
      "I got pink toes runnin' 'round the house",
      'I thank God I understand the way it go (I understand)',
      'She a damn crew hopper, XO, yeah',
      "High speed chasin' in that Lamborghini Turbo S (Rrt)",
      'How come these niggas tryna tell me that they been fresh? (Hah)',
      "I got money tied up in killin' (Ah)",
      'Try not to let bygones be bygones and (Brrt)',
      "Thinkin' I'm a lick, he choppin' off your tongue (Brr)",
      'Get over it, nah, nah, nah, nah, ayy (Nah, ayy)',
      "I can't seem to get over the sound of guns (Brr)",
      "I'm a drug addict, I know I got dead lungs (Woo)",
      'I pop Addies, my diamonds black, Akon (My diamonds Akon)',
      "I can't get over these hoes, I'm my mama's son (Yeah)",
      'I keep it drastic, she can only stay or run',
      'Fresh as a casket, but YSL look alive (Woo)',
      'If I get mad I promise they all die (Brrt)',
      'I told the boy to behave, he a small guy (Mhm)',
      "Brown diamonds chillin', no fries (Brown diamonds)",
      'Couple green diamonds, apple, no pies (Woah, woah)',
      "I'm drainin' and strainin' my voice until I get it right (Yeah)",
      "This money control us, yeah, one of us'll pick a fight (Fight)",
      "I told all the opps every time I see 'em it's on sight (On God)",
      "I caught your lil' lady down bad and ride her like a bike",
      'No cap (Uh-huh, no cap), ayy',
      "I'm fresh as fuck, I told that bitch I should've came in a hearse (Came in a hearse)",
      'I put Chanel on her ears and on her neck and her purse (Neck and her purse)',
      "I'm number one, my birthday should've been January the first, woah (January the first)",
      'Oh (Yeah, yeah, yeah, January)',
      'I got diamonds from my toes up to my top (Top)',
      "I got pink toes runnin' 'round the house (House)",
      'I thank God I understand the way it go (I understand, yeah)',
      'She a damn crew hopper, XO, yeah (Yeah)',
    ],
  },
  {
    id: '8db32560-b9a1-46ba-8bd4-e1b7386d7124',
    song: {
      artist_names: 'Metro Boomin, Travis Scott \u0026 Young Thug',
      full_title: 'Trance (ChoppedNotSlopped) by Metro Boomin, Travis Scott \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.1000x1000x1.jpg',
      id: 0,
      uuid: '8838449',
      path: '/Metro-boomin-travis-scott-and-young-thug-trance-choppednotslopped-lyrics',
      release_date_for_display: 'February 17, 2023',
      song_art_image_thumbnail_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.1000x1000x1.jpg',
      title: 'Trance (ChoppedNotSlopped)',
      url: 'https://genius.com/Metro-boomin-travis-scott-and-young-thug-trance-choppednotslopped-lyrics',
    },
    lyrics: [
      "Ah, take off the top, baby, let's ride",
      "I'm with my dawgs, I pick the side",
      'She want the boss, the one own the tribe',
      'I own the tribe, yeah',
      'Arm out the window, just throw it when we ride',
      'I bent the corner, scraped the wheel and the tires (Woo)',
      "Put twenty hoes on a boat 'til they tired",
      'Everybody on (On)',
      'You-you know you need me, my nigga',
      "Just keep this sh-shit real, don't you cry, what you saw? (Need)",
      "Who-who else fuck up the city like us? When it-it rain, it's a thunderstorm (Thunderstorm)",
      "I par-I party at Shabba in New York and L.A. where they keep on goin' to the dawn (Shabba)",
      "Two-two hundred K what I'm on (Two hundred)",
      "She lick–, she lickin' all down my chest (Down my, lick down my chest, yeah, yeah)",
      'I told her, "I ain\'t Slime, baby, call me SEX," yeah (I\'m not Slime, just call me SEX)',
      "It ain't no dope where I put these racks at, yeah (Ain't no dope where I put these racks)",
      'If you my ho, I call you sexy, yeah (If you my ho, I call you sexy)',
      "Goddamn, lately she so bad, it's dangerous (Dangerous)",
      'I backed out of the knot, she tried to tangle up (Uh)',
      "She got Paris manners and it's so dangerous (Dangerous)",
      'Uh, uh, uh, uh, uh',
      "Caught in a trance, it's givin' us (Yeah, ah)",
      "Caught in a trance, it's givin' us (Ah, yeah, uh-huh)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      'Late night, late night, late night',
      'To the side, to the side',
      'Yeah, yeah, this side',
      'You got riptide in mind',
      'I move so far in time',
      'I move so far in time (Ooh)',
      'I been whipped up at night (Woah, ooh)',
      'I been whipped up at night',
      'With my fists up, in drive (Drive, ooh)',
      "Drivin', **** up, in time (Ooh, yeah)",
      'I been pimped up– (Uh)',
    ],
  },
  {
    id: '74cdfcc5-387a-4ba2-b099-2ed8c47a385d',
    song: {
      artist_names: 'Young Thug (Ft. Rich Homie Quan)',
      full_title: 'Color Purple by Young Thug (Ft. Rich Homie Quan)',
      header_image_thumbnail_url: 'https://images.genius.com/3a1ed2788d29f7ad79a014925a1f0613.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/3a1ed2788d29f7ad79a014925a1f0613.640x640x1.jpg',
      id: 0,
      uuid: '2340961',
      path: '/Young-thug-color-purple-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/3a1ed2788d29f7ad79a014925a1f0613.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/3a1ed2788d29f7ad79a014925a1f0613.640x640x1.jpg',
      title: 'Color Purple',
      url: 'https://genius.com/Young-thug-color-purple-lyrics',
    },
    lyrics: [
      'Yeah, ayy',
      "Drinkin' color purple, ceiling color purple, ridin' color purple",
      'What? What?',
      'Hey, Oprah Winfrey bring me that color purple',
      'Ayy, Danny Glover bring me that color purple',
      'Oh, double cup fill it up with color purple',
      'Color purple',
      'Bring that color purple, color purple, color purple',
      'Bring that color purple',
      'That color purple, bring that color purple',
      'Bring that color purple, color purple, color purple',
      "Drinkin' color purple, smokin' color purple",
      "Bring it over when I'm nursin'",
      'Quan off the surface',
      "Which one you workin', what you sellin'? I'ma purchase",
      "I am never earthin', ballin' like I'm nerfin'",
      'Man I shoot that nig in person',
      "Killin' what you worthin'",
      'Break in baby purses',
      'Draped in clothes like some curtains',
      'Oh, lil\' boo says "oh"',
      "I'll bite you soon when I get home",
      "I'm fly as a broom",
      "Take off while sippin' on champagne",
      'Oh, these bitches all like my domain',
      'Hey, hey, oh',
      'Hey, Oprah Winfrey bring me that color purple',
      'Ayy, Danny Glover bring me that color purple',
      'Oh, double cup fill it up with color purple',
      'Color purple',
      'Bring that color purple, color purple, color purple',
      'Bring that color purple',
      'That color purple, bring that color purple',
      'Bring that color purple, color purple, color purple',
      "Keep me ridin' in it, I could whip a belly too big for a loaf",
      "Purple with the Remy, fuck her in the rental and it never comin' off",
      "All my cars are tinted, you can't see what's in it then I'm ridin' off",
      "Presidential lil' skeet all in her mouth",
      'Why your bitch gets one look, leach on a nigga, boss',
      "Why the hell the lil' bitch wanna bring two bihs to daddy house?",
      'Do the lil\' bitch wanna play games? I\'ma make her say "wow"',
      "Lil' destiny, no child",
      'Ayy, your music so chow',
      "I'm ___ just like a flower",
      "I'm only purple just like a flower",
      'I got front coach, so I come with towels',
      'Hey, Oprah Winfrey bring me that color purple',
      'Ayy, Danny Glover bring me that color purple',
      'Oh, double cup fill it up with color purple',
      'Color purple',
      'Bring that color purple, color purple, color purple',
      'Bring that color purple',
      'That color purple, bring that color purple',
      'Bring that color purple, color purple, color purple',
    ],
  },
  {
    id: '07937ac5-9914-43b0-ad16-a64ebcc3c025',
    song: {
      artist_names: 'Gucci Mane \u0026 Young Thug (Ft. Peewee Longway)',
      full_title: 'Took By a Bitch by Gucci Mane \u0026 Young Thug (Ft. Peewee Longway)',
      header_image_thumbnail_url: 'https://images.genius.com/742637f99fa18db91cec96a6d2a683f4.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/742637f99fa18db91cec96a6d2a683f4.500x500x1.jpg',
      id: 0,
      uuid: '658985',
      path: '/Gucci-mane-and-young-thug-took-by-a-bitch-lyrics',
      release_date_for_display: 'April 20, 2014',
      song_art_image_thumbnail_url: 'https://images.genius.com/742637f99fa18db91cec96a6d2a683f4.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/742637f99fa18db91cec96a6d2a683f4.500x500x1.jpg',
      title: 'Took By a Bitch',
      url: 'https://genius.com/Gucci-mane-and-young-thug-took-by-a-bitch-lyrics',
    },
    lyrics: [
      'Trench coat with a AK inside that (Brrat, brra)',
      "Where the sack at? You can't hide that (I smell it)",
      'Gotta provide that',
      "If getting money was on your agenda, please erase it (Don't write it down)",
      "Ain't gotta do nothing, I got young killers that's gonna come take it (My niggas)",
      'Yeah, your money getting took by a bitch (Yeah, yeah)',
      'Said yeah, your money getting took by a bitch, boy (Oh yeah)',
      'You know your money getting took by a bitch (Take that shit, baby, Longway)',
      'Did you know your money would get took by a bitch, boy? (Take that shit)',
      'Trench coat with a AK inside that (Brrat, brra)',
      "Where the sack at? You can't hide that (I smell it)",
      'Gotta provide that',
      "If getting money was on your agenda, please erase it (Don't write it down)",
      "Ain't gotta do nothing, I got young killers that's gonna come take it (My niggas)",
      'Yeah, your money getting took by a bitch (Yeah, yeah)',
      'Said yeah, your money getting took by a bitch, boy (Oh yeah)',
      'You know your money getting took by a bitch (Take that shit, baby)',
      'Did you know your money would get took by a bitch, boy? (Take that shit)',
    ],
  },
  {
    id: '7e452f4c-4638-4fab-84fd-450e53b50272',
    song: {
      artist_names: 'Rich Homie Quan (Ft. Young Thug)',
      full_title: 'Aye by Rich Homie Quan (Ft. Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/f15def3ae8a3d8e34f41d71d64242e68.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/f15def3ae8a3d8e34f41d71d64242e68.640x640x1.jpg',
      id: 0,
      uuid: '625093',
      path: '/Rich-homie-quan-aye-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/f15def3ae8a3d8e34f41d71d64242e68.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/f15def3ae8a3d8e34f41d71d64242e68.640x640x1.jpg',
      title: 'Aye',
      url: 'https://genius.com/Rich-homie-quan-aye-lyrics',
    },
    lyrics: [
      'I add mud with the soda, I drink lean, never sober',
      "We live life like Morgan Freeman, Quan leanin' on my shoulder",
      'Ooh, you niggas still green like a soldier',
      "I need me two like I'm pokin'",
      "At the concert, show 'em you clap it like Magnolia",
      "Ooh, you need to show 'em you the best at what you do (Turn up, turn up)",
      "I just took off, I'm on a mountain, girl, no Dew (Turn up, turn up)",
      'Ooh, she said she wanna party (What?)',
      'Young Quan voice, I leave these bitches with no choice',
      "I don't eat pork, I drink Smartwater like a dork (Woo)",
      "I'm not blowin' my money, lil' nigga, I'm not Scott Storch (Woo)",
      'Bought a bitch a Birkin bag, inside it was a Yorkie (Woo)',
      "You lil' niggas can't afford it, hey",
    ],
  },
  {
    id: '8db32560-b9a1-46ba-8bd4-e1b7386d7124',
    song: {
      artist_names: 'Metro Boomin, Travis Scott \u0026 Young Thug',
      full_title: 'Trance (ChoppedNotSlopped) by Metro Boomin, Travis Scott \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.1000x1000x1.jpg',
      id: 0,
      uuid: '8838449',
      path: '/Metro-boomin-travis-scott-and-young-thug-trance-choppednotslopped-lyrics',
      release_date_for_display: 'February 17, 2023',
      song_art_image_thumbnail_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/7360f3a5b01ea634e10608c6975d61d5.1000x1000x1.jpg',
      title: 'Trance (ChoppedNotSlopped)',
      url: 'https://genius.com/Metro-boomin-travis-scott-and-young-thug-trance-choppednotslopped-lyrics',
    },
    lyrics: [
      "Ah, take off the top, baby, let's ride",
      "I'm with my dawgs, I pick the side",
      'She want the boss, the one own the tribe',
      'I own the tribe, yeah',
      'Arm out the window, just throw it when we ride',
      'I bent the corner, scraped the wheel and the tires (Woo)',
      "Put twenty hoes on a boat 'til they tired",
      'Everybody on (On)',
      'You-you know you need me, my nigga',
      "Just keep this sh-shit real, don't you cry, what you saw? (Need)",
      "Who-who else fuck up the city like us? When it-it rain, it's a thunderstorm (Thunderstorm)",
      "I par-I party at Shabba in New York and L.A. where they keep on goin' to the dawn (Shabba)",
      "Two-two hundred K what I'm on (Two hundred)",
      "She lick–, she lickin' all down my chest (Down my, lick down my chest, yeah, yeah)",
      'I told her, "I ain\'t Slime, baby, call me SEX," yeah (I\'m not Slime, just call me SEX)',
      "It ain't no dope where I put these racks at, yeah (Ain't no dope where I put these racks)",
      'If you my ho, I call you sexy, yeah (If you my ho, I call you sexy)',
      "Goddamn, lately she so bad, it's dangerous (Dangerous)",
      'I backed out of the knot, she tried to tangle up (Uh)',
      "She got Paris manners and it's so dangerous (Dangerous)",
      'Uh, uh, uh, uh, uh',
      "Caught in a trance, it's givin' us (Yeah, ah)",
      "Caught in a trance, it's givin' us (Ah, yeah, uh-huh)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      "Caught in a trance, it's givin' us (Ah)",
      'Late night, late night, late night',
      'To the side, to the side',
      'Yeah, yeah, this side',
      'You got riptide in mind',
      'I move so far in time',
      'I move so far in time (Ooh)',
      'I been whipped up at night (Woah, ooh)',
      'I been whipped up at night',
      'With my fists up, in drive (Drive, ooh)',
      "Drivin', **** up, in time (Ooh, yeah)",
      'I been pimped up– (Uh)',
    ],
  },
  {
    id: '9cc62b48-eac5-41d7-a2c7-d0953dbb4dfd',
    song: {
      artist_names: 'T.I. (Ft. Jeezy, Lil Wayne \u0026 Young Thug)',
      full_title: 'All About da Money (Remix) by T.I. (Ft. Jeezy, Lil Wayne \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.500x500x1.jpg',
      id: 0,
      uuid: '552676',
      path: '/Ti-all-about-da-money-remix-lyrics',
      release_date_for_display: 'October 24, 2014',
      song_art_image_thumbnail_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.500x500x1.jpg',
      title: 'All About da Money (Remix)',
      url: 'https://genius.com/Ti-all-about-da-money-remix-lyrics',
    },
    lyrics: [
      "What you think I'm standin' in the trap for? (why?)",
      'With the fully automatic at the back door',
      "'Cause when it's on, know it's on, call me King Corleone (ooh!)",
      "I'mma keep it 1000 like a crack ounce",
      "Give a damn if I'm flat broke (nah!)",
      "I'm filthy rich, I'm still the same, that's a fact though",
      'Oh yeah, we all about the money, nigga',
      'All you got is money when my name hold weight like a fat ho',
      "I can never join in the game 'less I'm capo",
      "Milkin' these niggas even though I'm fuckin' lactose",
      'Take off on the cops, Mama said, "Don\'t look back, bro"',
      "I'm in New York and I'm ballin' just like a Net, though",
      "I'm drinkin' bubblegum pink like Pepto",
      'Bismol, bet she wanna come through',
      "And get low, I'ma be with Haitians",
      'All my Zos, Tip tell these niggas, bro',
      'Bankroll Mob, yeah, we on, we retarded',
      "I'ma give you 15 from the carbine (turn it!)",
      'Hit you in the leg, in your head, then your face',
      "When you dead, bet ya I'ma take your place on the Forbes list",
      'So better miss with that bullshit, partner',
      "I'll be hopping out your bushes with a full clip, got 'em (got 'em!)",
      "I'll take a big stick to a fuck nigga neck (nigga neck!)",
      'Swinging at it, kind of like a piñata',
      'I get money on a very rainy day (and!)',
      'I would love to spray your face with Olay, aye',
      'No computer cause she never wanted space, aye',
      "I swear lil' mama is the weirdest in the place, ayy",
      "I'm a big G, dinosaur B",
      "You know, YSL takin' over streets",
      "I'm a K-Ci, where is Jodeci?",
      "I'ma treat em' bad like he supposed to be",
      "I'm a blood, nigga, don't try to approach me",
      "Girl, let's hit like Kobe and Ginobili",
      "If them not Gucci earmuffs, you can't ignore me",
      'Her booty piped up like a circus, baby, show me',
      "I might just take off on that broad 'cause she don't know me",
      'Dej Loaf, change that beef to macaroni',
      "No scale, but my bitches say I'm bony",
      'Lil mama still blushing at the old me (woo!)',
    ],
  },
  {
    id: 'dd85bf83-7d40-420d-a3f5-c42bcace817e',
    song: {
      artist_names: 'Young Stoner Life \u0026 Young Thug',
      full_title: 'Tsunami by Young Stoner Life \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/d6f290a6eeac941536865f2df98adc11.300x169x1.jpg',
      header_image_url: 'https://images.genius.com/d6f290a6eeac941536865f2df98adc11.1000x563x1.jpg',
      id: 0,
      uuid: '3902296',
      path: '/Young-stoner-life-and-young-thug-tsunami-lyrics',
      release_date_for_display: 'August 17, 2018',
      song_art_image_thumbnail_url: 'https://images.genius.com/f1cb107d4a623f18ffe59da7c0a1d8a8.300x300x1.png',
      song_art_image_url: 'https://images.genius.com/f1cb107d4a623f18ffe59da7c0a1d8a8.1000x1000x1.png',
      title: 'Tsunami',
      url: 'https://genius.com/Young-stoner-life-and-young-thug-tsunami-lyrics',
    },
    lyrics: [
      'Yeah',
      '(Wheezy outta here)',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Tsunami wave',
      'Wheezy the wave',
      'Tsunami wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
      "Hundred thousand E's",
      'I pull up with a hundred pounds of weed',
      "Aviator Chanel, double C's",
      'I got every single kind out, ha',
      "Told this girl ain't no timeout, uh",
      "I perfected this rhymin'",
      "Nothin' but foreigns I'm ridin' in",
      "Finally rich and it's showin'",
      "And I'm lettin' it",
      "I've been goin' near the sun lately",
      "Everything that I'm in, yeah, it came, yeah",
      'I got twenty-six Cuban Doll chains, yeah',
      "Nigga takin' this shit down, sunset",
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
      'I like the way she give head',
      'I call her Mitchell \u0026amp; Ness',
      'I keep a drum on the TEC (Brrat)',
      'I gotta protect all my kids (Brrat)',
      "I don't need no help with this (Brrat)",
      'Bitch, put my kids on your tits (Brrat-brrat)',
      'I put your name on my wrist',
      'Fat Richard Mille on my wrist',
      'See my bag, bitch, see my bitch behind me',
      'Gold diamonds with—',
      'Match the sidekick',
      "I made promises and I'm keepin' it",
      'Get the Range Rover, autobiography',
      "Talkin' crazy, slap his ass with the shine (Brrt)",
      'Put the light-up wrist at any time (Brrt)',
      'Ric Flair with the times, ew',
      "Big B's everywhere, suuwoo, brrt, brrt",
      'Shawty said I be the realest',
      "Can't get enough of this killin'",
      'The weed that I smoke smell like chitlins',
      "Boosie and Webbie, I'm trillest",
      'I been tied in with the killers',
      'I been tied in with the dealers',
      'I put some rings on my fingers',
      "Hand shinin' like the Thriller",
      "Whippin' it, go grab the trigger",
      'Foreigns behind me, BMF',
      "Boardin' the jet with the real plug",
      'Two hundred racks off skrilla',
      'Red bottoms, she a killer',
      'Red bottoms, she a killer',
      "Gucci slides for the chillin'",
      'Jimmy Choo when I miss her',
      'Three times a week, nails',
      "Shawty takin' good care",
      'Wheezy wave, papa bear',
      'Young Keyyz go Alicia',
      'Who your man? Oh well',
      'I could never never tell',
      "And I'm tryna do well",
      'Buy Chanels for your tears',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Tsunami wave',
      'Wheezy the wave',
      'Tsunami wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
    ],
  },
  {
    id: 'dd85bf83-7d40-420d-a3f5-c42bcace817e',
    song: {
      artist_names: 'Young Stoner Life \u0026 Young Thug',
      full_title: 'Tsunami by Young Stoner Life \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/d6f290a6eeac941536865f2df98adc11.300x169x1.jpg',
      header_image_url: 'https://images.genius.com/d6f290a6eeac941536865f2df98adc11.1000x563x1.jpg',
      id: 0,
      uuid: '3902296',
      path: '/Young-stoner-life-and-young-thug-tsunami-lyrics',
      release_date_for_display: 'August 17, 2018',
      song_art_image_thumbnail_url: 'https://images.genius.com/f1cb107d4a623f18ffe59da7c0a1d8a8.300x300x1.png',
      song_art_image_url: 'https://images.genius.com/f1cb107d4a623f18ffe59da7c0a1d8a8.1000x1000x1.png',
      title: 'Tsunami',
      url: 'https://genius.com/Young-stoner-life-and-young-thug-tsunami-lyrics',
    },
    lyrics: [
      'Yeah',
      '(Wheezy outta here)',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Tsunami wave',
      'Wheezy the wave',
      'Tsunami wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
      "Hundred thousand E's",
      'I pull up with a hundred pounds of weed',
      "Aviator Chanel, double C's",
      'I got every single kind out, ha',
      "Told this girl ain't no timeout, uh",
      "I perfected this rhymin'",
      "Nothin' but foreigns I'm ridin' in",
      "Finally rich and it's showin'",
      "And I'm lettin' it",
      "I've been goin' near the sun lately",
      "Everything that I'm in, yeah, it came, yeah",
      'I got twenty-six Cuban Doll chains, yeah',
      "Nigga takin' this shit down, sunset",
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
      'I like the way she give head',
      'I call her Mitchell \u0026amp; Ness',
      'I keep a drum on the TEC (Brrat)',
      'I gotta protect all my kids (Brrat)',
      "I don't need no help with this (Brrat)",
      'Bitch, put my kids on your tits (Brrat-brrat)',
      'I put your name on my wrist',
      'Fat Richard Mille on my wrist',
      'See my bag, bitch, see my bitch behind me',
      'Gold diamonds with—',
      'Match the sidekick',
      "I made promises and I'm keepin' it",
      'Get the Range Rover, autobiography',
      "Talkin' crazy, slap his ass with the shine (Brrt)",
      'Put the light-up wrist at any time (Brrt)',
      'Ric Flair with the times, ew',
      "Big B's everywhere, suuwoo, brrt, brrt",
      'Shawty said I be the realest',
      "Can't get enough of this killin'",
      'The weed that I smoke smell like chitlins',
      "Boosie and Webbie, I'm trillest",
      'I been tied in with the killers',
      'I been tied in with the dealers',
      'I put some rings on my fingers',
      "Hand shinin' like the Thriller",
      "Whippin' it, go grab the trigger",
      'Foreigns behind me, BMF',
      "Boardin' the jet with the real plug",
      'Two hundred racks off skrilla',
      'Red bottoms, she a killer',
      'Red bottoms, she a killer',
      "Gucci slides for the chillin'",
      'Jimmy Choo when I miss her',
      'Three times a week, nails',
      "Shawty takin' good care",
      'Wheezy wave, papa bear',
      'Young Keyyz go Alicia',
      'Who your man? Oh well',
      'I could never never tell',
      "And I'm tryna do well",
      'Buy Chanels for your tears',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Young Wheezy the wave',
      'Wheezy the wave',
      'Wheezy the wave',
      'Young Wheezy the wave',
      'Tsunami wave',
      'Wheezy the wave',
      'Tsunami wave',
      'If you tryna fuck in one night all the dawgs',
      'Young Aviator Keyyz gotta pass along',
      "Young Aviator Keyyz never stoppin'",
      'Aviator Keyyz right behind me',
      'Aviator Keyyz change the climate',
    ],
  },
  {
    id: 'edbbb392-aeae-4a1f-b3a0-29b5adab4407',
    song: {
      artist_names: 'YoungBoy Never Broke Again (Ft. Gunna \u0026 Young Thug)',
      full_title: 'All My Hoes by YoungBoy Never Broke Again (Ft. Gunna \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.640x640x1.jpg',
      id: 0,
      uuid: '5854133',
      path: '/Youngboy-never-broke-again-all-my-hoes-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/8c2d7e15c061a19cc0f136eb9da5565d.640x640x1.jpg',
      title: 'All My Hoes',
      url: 'https://genius.com/Youngboy-never-broke-again-all-my-hoes-lyrics',
    },
    lyrics: [
      "I'll put a Patek Philippe on your head (Ayy)",
      'I got twenty bitches in my jet, dog (In my bed, dog)',
      "I'm missing molly with my med (Yeah)",
      'Put a couple extras in my red (Woo)',
      'Come and kill everything but the kids (Woo)',
      'Bring me the head and everything else get rid (Woo)',
      "Gold on my teeth, the reason I smile, I'm never kiddin' (Woah)",
      "'Bout to pull up on your block, hop out my car, get in your shit (Yeah)",
      'My mama told you I was a star (My mama told you)',
      "I bought my mansion accordin' to my calls (Yeah)",
      '___ been with me ever since this morning',
      "We just rippin' around this bitch, we ain't doin' nothin' but stuntin' (Turn up)",
      'Got big baguettes in every single one of my chains (Every single one), ayy',
      "Spend a big ol' check on every single one of my mains (Uh, facts)",
      "I tried to tell you it's no cap inside my game, no (No cap inside my game)",
      "I'm swervin' the whole street, ain't got no lane, no (Skrrt, skrrt)",
    ],
  },
  {
    id: 'cdbef7dc-b4f0-4288-bc30-b027c3fa3849',
    song: {
      artist_names: 'Gucci Mane (Ft. Young Thug)',
      full_title: '1017 Mafia by Gucci Mane (Ft. Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/4937bacb56e3a42d2229420322f0dbc1.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/4937bacb56e3a42d2229420322f0dbc1.640x640x1.jpg',
      id: 0,
      uuid: '661289',
      path: '/Gucci-mane-1017-mafia-lyrics',
      release_date_for_display: 'January 3, 2015',
      song_art_image_thumbnail_url: 'https://images.genius.com/4937bacb56e3a42d2229420322f0dbc1.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/4937bacb56e3a42d2229420322f0dbc1.640x640x1.jpg',
      title: '1017 Mafia',
      url: 'https://genius.com/Gucci-mane-1017-mafia-lyrics',
    },
    lyrics: [
      'Thugga and Guwop got 100 choppas',
      '1017 we the, Mafia',
      "We the motherfuckin' mafia nigga",
      'No less than 20 in my trousers lil nigga',
      'Got these bitches bending over like a lineman',
      'Make the pot, bitch straight over like a linemen',
      'Everybody get that green, we the live men',
      'All my slime crickets, I think we need lemons',
      '1017 the mothafucking movement',
      "Pipe that bitch down, I'ma duel it",
      'The way I  throw em through  it, my arm  a Uzi',
      'Bought a bitch a pair of shoes, and fuck her booty',
      "Hol'  it, don't let up, these niggas can't catch with thugga no thugger",
      "We eatin' no other",
      "I'm chubby like my brother",
      "I'm chubby like my mother",
      'We take all yo goodies, and go straight to Costco',
      'Catch up with yo bitch, and turn her into a sucka',
      'We not overseas but you know we Russian',
      'Picnic early, clubbin later',
      "I'm not no candy,  but I am a jawbreaker",
      "You think I'm gay,  I'ma send ya to meet your maker",
      "Put a hole in yo head like you's  a piston",
      'Thugga and Guwop got 100 choppas',
      '1017 we the, Mafia',
      "We the motherfuckin' mafia nigga",
      'No less than 20 in my trousers lil nigga',
      'Thugga and Guwop got 100 choppas',
      '1017 we the, Mafia',
      "We the motherfuckin' mafia nigga",
      'No less than 20 in my trousers lil nigga',
    ],
  },
  {
    id: '9cc62b48-eac5-41d7-a2c7-d0953dbb4dfd',
    song: {
      artist_names: 'T.I. (Ft. Jeezy, Lil Wayne \u0026 Young Thug)',
      full_title: 'All About da Money (Remix) by T.I. (Ft. Jeezy, Lil Wayne \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.500x500x1.jpg',
      id: 0,
      uuid: '552676',
      path: '/Ti-all-about-da-money-remix-lyrics',
      release_date_for_display: 'October 24, 2014',
      song_art_image_thumbnail_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/f1fd1fd9739e15ac43d224e316cb4e93.500x500x1.jpg',
      title: 'All About da Money (Remix)',
      url: 'https://genius.com/Ti-all-about-da-money-remix-lyrics',
    },
    lyrics: [
      "What you think I'm standin' in the trap for? (why?)",
      'With the fully automatic at the back door',
      "'Cause when it's on, know it's on, call me King Corleone (ooh!)",
      "I'mma keep it 1000 like a crack ounce",
      "Give a damn if I'm flat broke (nah!)",
      "I'm filthy rich, I'm still the same, that's a fact though",
      'Oh yeah, we all about the money, nigga',
      'All you got is money when my name hold weight like a fat ho',
      "I can never join in the game 'less I'm capo",
      "Milkin' these niggas even though I'm fuckin' lactose",
      'Take off on the cops, Mama said, "Don\'t look back, bro"',
      "I'm in New York and I'm ballin' just like a Net, though",
      "I'm drinkin' bubblegum pink like Pepto",
      'Bismol, bet she wanna come through',
      "And get low, I'ma be with Haitians",
      'All my Zos, Tip tell these niggas, bro',
      'Bankroll Mob, yeah, we on, we retarded',
      "I'ma give you 15 from the carbine (turn it!)",
      'Hit you in the leg, in your head, then your face',
      "When you dead, bet ya I'ma take your place on the Forbes list",
      'So better miss with that bullshit, partner',
      "I'll be hopping out your bushes with a full clip, got 'em (got 'em!)",
      "I'll take a big stick to a fuck nigga neck (nigga neck!)",
      'Swinging at it, kind of like a piñata',
      'I get money on a very rainy day (and!)',
      'I would love to spray your face with Olay, aye',
      'No computer cause she never wanted space, aye',
      "I swear lil' mama is the weirdest in the place, ayy",
      "I'm a big G, dinosaur B",
      "You know, YSL takin' over streets",
      "I'm a K-Ci, where is Jodeci?",
      "I'ma treat em' bad like he supposed to be",
      "I'm a blood, nigga, don't try to approach me",
      "Girl, let's hit like Kobe and Ginobili",
      "If them not Gucci earmuffs, you can't ignore me",
      'Her booty piped up like a circus, baby, show me',
      "I might just take off on that broad 'cause she don't know me",
      'Dej Loaf, change that beef to macaroni',
      "No scale, but my bitches say I'm bony",
      'Lil mama still blushing at the old me (woo!)',
    ],
  },
  {
    id: '99cb2c9c-631e-492c-9fc2-eecb30bbe885',
    song: {
      artist_names: 'Young Thug',
      full_title: 'All I Want by Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.300x299x1.png',
      header_image_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.721x719x1.png',
      id: 0,
      uuid: '9659118',
      path: '/Young-thug-all-i-want-lyrics',
      release_date_for_display: '2011',
      song_art_image_thumbnail_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.300x299x1.png',
      song_art_image_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.721x719x1.png',
      title: 'All I Want',
      url: 'https://genius.com/Young-thug-all-i-want-lyrics',
    },
    lyrics: [],
  },
  {
    id: 'd2a2b1e1-690e-4a72-8834-7536ea37d79c',
    song: {
      artist_names: 'Future \u0026 Young Thug',
      full_title: 'All da Smoke by Future \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      id: 0,
      uuid: '3280973',
      path: '/Future-and-young-thug-all-da-smoke-lyrics',
      release_date_for_display: 'October 20, 2017',
      song_art_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      title: 'All da Smoke',
      url: 'https://genius.com/Future-and-young-thug-all-da-smoke-lyrics',
    },
    lyrics: [
      "You it, I'm it, everybody it",
      'We want all the smoke',
      "We want all the smoke (How it 'posed to)",
      'We want all the smoke',
      'We want all the smoke, smoke',
      'Yeah he just, he just breaking up the ice',
      'We leaning, facts',
      'Yeah',
      'Slatt',
      "Stackin' it tall (Thugger)",
      'Every nigga out my city became a boss (Became)',
      'Dolce, Rollie, holy moly, no days off (Woo, woo)',
      "Pyrex, cook it up like Kyrie, trade you off (Let's go)",
      "Green and white like Celtics, don't play with me, play with a fork (Play with a woop)",
      "I'm superior, I'm imperial, I ain't feelin' you (Ooh)",
      'I could eat me some heroin or buy a brick (Yeah, yeah)',
      'I got Barry Bonds on my wrist (Yeah)',
      'Blowed your college fund (Where?), on my bitch (Woo, woo)',
      'Out the slums, taking a chance, toting tommy guns (Brrt)',
      'Left out of school, started selling rocks, bought me a drop (Skrrt)',
      'Cartier frames, Cartier rings, Cartier socks (On God)',
      "Homicide Gang, they gon' put you on Fox (Homicide, Homicide)",
      "Putang ran up a whole M sittin' in the box (Facts)",
      'My dog rock a Rollie in the feds, nigga, and still move blocks (Facts)',
      "We had the bando goin' crazy in the SWAT's (In the where?)",
      "Ten-four, they runnin' up on all the opps",
      'We want all the smoke (Yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Aw yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Huh)',
      'This money turning me on, ayy',
      'This money turning me on (On, turn me on)',
      "I'm thinkin' out loud, but these hundreds got a nigga gone (Woo)",
      "Far gone, I'm so gone on it",
      'Three hundred racks for a Bentley truck, yeah yeah',
      "Take the factories off and go'n and lift it up, yeah yeah (Lift it up)",
      'Cash all on your bitch, she on the living room floor (Yeah)',
      'Having a private party, you know how that go (Let go)',
      'Music all in my ears (Yeah), instruments in my ears (What)',
      "I'm in the backyard feeding deers (Then what?)",
      "I'm in a penthouse poppin' seals (Then what?)",
      'I got pom-poms in my rear (Woo)',
      'Chanel CoCo in my dear (CoCo)',
      'I missed a couple shows for my deal',
      "If I could take it back I will (If I could take it back on 'em)",
      "And don't you take that to the head (No)",
      'You know I got you in my will (Yeah)',
      'Told big dawg bring the bricks in',
      'Got a hundred more at the crib (Ayy)',
      'Make the dope do the windmill (Yeah)',
      'Nigga swing through at your wheels (Brrt)',
      'They done quoted two on killed',
      "And I was in Miami countin' a mil' (Ayy)",
      'I told my bitch, "No more ass shots"',
      "She stopped all the way like a stop sign when it's traffic time",
      'My diamonds dark brown like Budweiser (Like Budweiser)',
      'Count a half a mil with my bitch, now her feelings sloppy (Yeah, yeah)',
      "Came up out the projects, ain't have shit, yeah (On God)",
      'I wiped a nigga nose for a ticket (Slime)',
      'Hit it from the back (Yeah)',
      'Make her say slime, say slatt (Yeah, yeah)',
      'How you dig that?',
      'Whipped up the fish Parkay and got racks, ayy',
      'We want all the smoke',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke (Yeah)',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
      'We want all the smoke',
    ],
  },
  {
    id: 'a0c15961-7962-4563-8e51-a9e5807790ff',
    song: {
      artist_names: 'Stackzz (Ft. Peewee Longway \u0026 Young Thug)',
      full_title: '36 by Stackzz (Ft. Peewee Longway \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/69be3d22be298546a281be99e4c6ddcd.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/69be3d22be298546a281be99e4c6ddcd.1000x1000x1.jpg',
      id: 0,
      uuid: '460949',
      path: '/Stackzz-36-lyrics',
      release_date_for_display: 'June 3, 2014',
      song_art_image_thumbnail_url: 'https://images.genius.com/69be3d22be298546a281be99e4c6ddcd.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/69be3d22be298546a281be99e4c6ddcd.1000x1000x1.jpg',
      title: '36',
      url: 'https://genius.com/Stackzz-36-lyrics',
    },
    lyrics: [
      'Andale, Andale, Andale',
      'Young Bone n Thug, no harmony',
      "And I'm not a real falcon fan, but I see birds every sunday",
      'Hey, Magic City Monday, no sofa my voice persuade',
      'These bitches they bring me they digits, I fuck them and leave them in holes, no ditches',
      "Sorry for the sin no city, I'm living like Dennis the Menace",
      'She told me I treat her like she was locked up, I only give a couple visits',
      "Ooh I'm bleeding, need a bandana I'm too bool",
      'Listen, In the kitchen with a hundred ___ revving revving revving like cyborg nigga',
      "Like a black diamond running 'round looking like the fucking knight",
      'Got a bitch with me, she not American but she my Idol',
      "And I'ma beat that pussy, I'ma eat that pussy, I'ma cook that cinnamon white",
    ],
  },
  {
    id: '5e4fc70a-3956-42b6-a57d-885c7e51c2b2',
    song: {
      artist_names: 'Future \u0026 Young Thug',
      full_title: 'Three by Future \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      id: 0,
      uuid: '3280969',
      path: '/Future-and-young-thug-three-lyrics',
      release_date_for_display: 'October 20, 2017',
      song_art_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      title: 'Three',
      url: 'https://genius.com/Future-and-young-thug-three-lyrics',
    },
    lyrics: [
      'DY Krazy',
      'Peter Piper pepper, I never kept her',
      "Peter Piper pepper, we never kept 'em",
      'Yeah',
      'I got more bracelets on than you got chains, bro',
      "Me and my dawg's dope came in on the same boat",
      "Whippin' the same dope, I put the bitch in the eighth stroke",
      'Right out the ghetto, too rap for the Leto, yeah',
      'Caught my first body out a Bentley coupe, yeah',
      'Ten real murders from my migos, yeah',
      'Rock the Cuban link down to my knees, yeah, yeah',
      'Ostrich seats, bite your sleeves, yeah, yeah',
      "Trippin' 'em up like I'm refereein' with these gators (Yeah)",
      'Triple my spot, it was no more basic cable (Yeah)',
      "I mixed some Act' with some yellow 'Tuss like a Laker (Yeah)",
      "Three shot 'em like a motherfuckin' Pacer (Southside, yeah, yeah)",
      "Never lose like I'm motherfuckin' McGregor (Yeah)",
      'Inside the whips come red like ketchurp (Yeah)',
      'Count this money up with glasses like a niz-zerd  (Yeah)',
      "Codeine laboratory like I'm Dexter",
      "Bad yellow skin, Filipin'",
      'Envious and gin, never win',
      "Chrome Heart lens, help me see 'em",
      'Hit him in his back, South Central',
      "Made a lot of M's right from sinnin'",
      "Ready to smoke the pimp 'bout my winnin'",
      'I prefer the shrimp, tired of chicken',
      "Ever saw me limp? That's-",
    ],
  },
  {
    id: '99cb2c9c-631e-492c-9fc2-eecb30bbe885',
    song: {
      artist_names: 'Young Thug',
      full_title: 'All I Want by Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.300x299x1.png',
      header_image_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.721x719x1.png',
      id: 0,
      uuid: '9659118',
      path: '/Young-thug-all-i-want-lyrics',
      release_date_for_display: '2011',
      song_art_image_thumbnail_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.300x299x1.png',
      song_art_image_url: 'https://images.genius.com/3e7372c25964ebfc1c1dbe8f55c8707d.721x719x1.png',
      title: 'All I Want',
      url: 'https://genius.com/Young-thug-all-i-want-lyrics',
    },
    lyrics: [],
  },
  {
    id: '9471596c-4a15-4788-ae4d-a753e7493763',
    song: {
      artist_names: 'Young Stoner Life \u0026 Young Thug (Ft. Tracy T)',
      full_title: 'Audemar by Young Stoner Life \u0026 Young Thug (Ft. Tracy T)',
      header_image_thumbnail_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.1000x1000x1.jpg',
      id: 0,
      uuid: '3902323',
      path: '/Young-stoner-life-and-young-thug-audemar-lyrics',
      release_date_for_display: 'August 17, 2018',
      song_art_image_thumbnail_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/54b22adf2c79e1df9cb61a1db387ed4c.1000x1000x1.jpg',
      title: 'Audemar',
      url: 'https://genius.com/Young-stoner-life-and-young-thug-audemar-lyrics',
    },
    lyrics: [
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, (Jeffery) skrrt (Yeah)',
      "Ridin' in a new Maybach (Skrr)",
      'Dunk on his ho like Shaq (Yeah)',
      'Jimmy Choo shoes, relax (Hold on)',
      'Givenchy socks to match (Come on)',
      "I was just smokin' on thrax (Smokin' on thrax)",
      "Now I'm playin' with that sack (Catch me playin' with that sack)",
      'Pussy just fall in my lap (Just fall in my lap)',
      "Money just chasin' my back (Just chasin' my back)",
      'The gang came back with racks (Yeah)',
      "I'm ridin' 'round town with a Gat (Gat)",
      "I'll beat a nigga face with a bat (Grr)",
      'Pink slip, paper tag (Hey)',
      'I bought me the new Hellcat (Skrrt)',
      "I'm blowin' the new Hellcat (Skrrt, skrrt)",
      'I walk in the club, Hellcat (Skrrt, skrrt, skrrt)',
      'Eighty-five racks, Hellcat (Skrrt, skrrt, skrrt)',
      'I eat the steak with the crab cake (Hey)',
      'I stuck my D on her chest, yeah (Hey)',
      'Baby tip-drill with a passion (With a passion)',
      "Crib came rusty like trash can (Let's go, woo)",
      'I need my bags, man (Yeah)',
      "I'ma come through like Aladdin (Woo)",
      'Audemar jacket (Hold on)',
      "Audemar coupe was matchin' (Audemar, Audemar)",
      'Audemar black sand (Audemar)',
      'Audemar picked up Ritalin (Audemar Ritalin)',
      'Audemar Piguet',
      'I just got some Audemar thrax in (Audemar thrax in)',
      "All of your Act' stashed",
      "All of your ass gon' stash packs (Audemar stash packs)",
      "All of y'all ass fat",
      "Audemar with a passion (All of y'all ass fat)",
      'Audemar, Springfield',
      'Audemar, drop-top, Bel Air',
      "Audemar paralyzin' drip",
      'Audemar wheelchair',
      'Audemar handmade (Yeah)',
      'Audemar billionaire (Yeah)',
      'Audemar blue and red (Ho)',
      'Audemar float, yeah (Audemar)',
      'Audemar wristband',
      'Audemar, Rollie face Ric Flair (Audemar, Audemar)',
      'Audemar wrist splash',
      'Audemar splish, splish, splash (Audemar, Audemar)',
      'Audemar whiplash',
      'Shawty got Audemar big ass (Audemar, Audemar)',
      'Turned my chips to cash',
      "I don't mean to rack up the millions (Woo, woo, woo)",
      "Ridin' in a new Maybach (Skrr)",
      "Dunk on his ho like Shaq (Let's go)",
      'Jimmy Choo shoes, relax (Woo)',
      'Givenchy socks to match (Come on)',
      "I was just smokin' on thrax (Woo)",
      "Now I'm playin' with that sack (I'm playin' with that sack)",
      'Pussy just fall in my lap (Just fall in my)',
      "Money just chasin' my back (Just chasin' my back)",
      'The gang came back with racks (Woo)',
      "I'm ridin' 'round town with a Gat (Skrr)",
      "I'll beat a nigga face with a bat (Face with a bat)",
      'Pink slip, paper tag (Hey)',
      'I bought me the new Hellcat (Skrrt)',
      "I'm blowin' the new Hellcat (Hey)",
      'I walk in the club, Hellcat (Yah)',
      'Eighty-five racks Hellcat (Hold on, woah)',
      "Ridin' in a new Maybach (Ridin' a new)",
      "Dunk on his hoe like Shaq (Ridin' a new Maybach)",
      "Jimmy Choo shoes, relax (Ridin' a new)",
      "Givenchy socks to match (Ridin' a new Maybach)",
      "I was just smokin' on thrax (Ridin' a new)",
      "Now I'm playin' with that sack (Ridin' a new Maybach)",
      "Pussy just fall in my lap (Ridin' a new)",
      "Money just chasin' my back (Ridin' a new Maybach)",
      'The gang came back with racks (Woo)',
      "I'm ridin' 'round town with a gat (Skrr)",
      "I'll beat a nigga face with a bat (Face with a bat)",
      'Pink slip, paper tag (Hey)',
      'I bought me the new Hellcat (Skrrt)',
      "I'm blowin' the new Hellcat (Hey)",
      'I walk in the club, Hellcat (Yeah)',
      'Eighty-five racks Hellcat (Hold on)',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt, skrrt',
      'Skrrt, skrrt, skrrt',
    ],
  },
  {
    id: 'e0e1addf-1767-4da5-b51f-a15b9b6e93b1',
    song: {
      artist_names: 'Young Thug (Ft. JID)',
      full_title: 'Bad Baby (Compensating Demo) by Young Thug (Ft. JID)',
      header_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      id: 0,
      uuid: '9778326',
      path: '/Young-thug-bad-baby-compensating-demo-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      title: 'Bad Baby (Compensating Demo)',
      url: 'https://genius.com/Young-thug-bad-baby-compensating-demo-lyrics',
    },
    lyrics: [
      'Lyrics from Snippet',
      "You've been givin' niggas surgical head (You've been)",
      "You've been eatin' out a young nigga flesh (You've been)",
      "You might win the key to my chest (You've been)",
      "You might win, give a young nigga head (You've been)",
      'You might win the key to my chest',
      'You might win the key to my chest',
      'You might win the key to my chest',
      'You might win the key to my chest',
      "You bad, baby, from the back, baby (Let's go)",
      'I hope her heart experiencing the crash, baby',
      'I toast it up and pour it out the glass, baby (Pour)',
      'I tripled up, I doubled up, I ranned it up, that fucked it up',
      'The black and orange Aventador like Daffy Duck (Skrrt)',
      "I swerve Mercedes Benz 'cause my credentials up (Yeah)",
      'I told her I got my millions up, these racks, baby (Racks)',
      'This song is hard as goosebumps, rash, baby (Racks)',
      "I'm scorin' by the three, Steve Nash, baby (Yeah)",
      'A couple million fee, all cash, baby (Yeah)',
      'I eat all of your cheese and racks, baby (Ayy)',
      "I eat a lil' cheese like a snack, baby (Yeah)",
      'The orange and black seats, Daffy Duck (Ayy)',
      'Five-leaf clover, better luck',
      'Don\'t you ask, "Do I know you?" Never, yuh (Yeah, mmm)',
      "I've been flyer than a pelican, yeah (Let's go)",
      "You've been givin' niggas surgical head (You've been)",
      "You've been eatin' out a young nigga flesh (You've been)",
      "You might win the key to my chest (You've been)",
      "You might win, give a young nigga head (You've been)",
      'You might win the key to my chest',
      'You might win the key to my chest',
      'You might win the key to my chest',
      'You might win the key to my chest  (Uh, yeah)',
    ],
  },
  {
    id: 'a0aec3c8-c554-4807-8189-0a65486135d3',
    song: {
      artist_names: 'Future \u0026 Young Thug',
      full_title: '200 by Future \u0026 Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      id: 0,
      uuid: '3280975',
      path: '/Future-and-young-thug-200-lyrics',
      release_date_for_display: 'October 20, 2017',
      song_art_image_thumbnail_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/ac7afa411ba9ad7bb409e411dc5f4b0d.1000x1000x1.jpg',
      title: '200',
      url: 'https://genius.com/Future-and-young-thug-200-lyrics',
    },
    lyrics: [
      'Everything right',
      'Everything right',
      'Everything right',
      'Now everything right',
      'Fuck all these niggas',
      "Everything right, we rockin' Givenchy",
      "I only drink Actavis, I'm on a diet",
      "I'ma chase it like Usain",
      'All this money bring a nigga new pain',
      'Yeah, yeah',
      'I got at least 200 hoes',
      'Fresh to death, and I leave my car and then I doze',
      "Up and down the E-way, risk it all 'bout this dough",
      "And these hundreds ain't goin' nowhere like a mole",
      "I bought my moms a car, it felt amazin'",
      "My niggas bangin' burgundy like the Redskins",
      "I got all type of tattoos on my fuckin' shin",
      'I was in a white and red Maybach like peppermints',
      "I been blowed a mil' on jewelry, but it's past tense",
      "Supercharge it, make it sound like it's raggly",
      "I'm ridin' with the cutter, I'm Blood like my brothers and MAC-10",
      "Diamonds on me talkin', they harassin'",
      'No shoulda, could, and would, I got these racks in',
      'Came a long way from a shed',
      'Now we spend millions on cribs',
      "You get somethin' too, don't trip",
      "My eyes 'bout low as a brim",
      'I smoke the tree limb, tree limb',
      'No gang, big deal',
      "I'm tryna pop a wheelie in a Lamborghini, standin' on two wheels",
      'I got the racks on me now, could buy me a cruise ship',
      'I just got an iPhone 8 and I already stored it with 200 hoes',
      'You smell the money on me, come from off my clothes',
      "Majority of the 'fits I wear, you'll never find in stores",
      "You might as well go'n, on, on home",
      'Money long, long, long, long',
      'All the way up to Mercury',
      'Any time I come out, gotta at least step out with a three piece',
      "I've been in my bag lately",
      'Take three drugs at once, lately',
      'Got every shade of Tom Ford, I can spot fugazi',
      'I came out the slums, I',
      'Got Hermes in a headlock',
      "If she ain't up to par, she 'bout to get dead docked",
      'Between my diamonds and my fame, became so anxious',
      "I sit at the top of the throne, yeah, 'cause I'm righteous",
      "Got a few Vice Lords for some friends, some of 'em Disciples",
      "And can't nothin' come in between niggas like us (Yeah yeah), hey",
      'I got at least 200 hoes',
      'Fresh to death, and I leave my car and then I doze',
      "Up and down the E-way, risk it all 'bout this dough",
      "And these hundreds ain't goin' nowhere like a mole",
    ],
  },
  {
    id: '74c92c7e-1a2d-4570-b01d-9980e579d7c2',
    song: {
      artist_names: 'Young Thug',
      full_title: 'A Dozen Roses by Young Thug',
      header_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      id: 0,
      uuid: '9393960',
      path: '/Young-thug-a-dozen-roses-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/e2db0d855b420382275f002934246013.760x760x1.jpg',
      title: 'A Dozen Roses',
      url: 'https://genius.com/Young-thug-a-dozen-roses-lyrics',
    },
    lyrics: [
      'A dozen roses',
      'Yeah',
      "All type of roses and shit, ya know what I'm saying?",
      'Red flowers, red roses, purple roses',
      "Candles and shit, lit it up, ya know what I'm saying?",
      "Smell good for these ho's",
      'Boss',
      'Vacuum seal the plastic (Vacuum seal the plastic)',
      "Shippin' and handlin' it (Yeah)",
      'Ship it off and stamp it (Ship it off)',
      'All my bitches ratchet (All my bitches ratchet)',
      'My car titanium',
      'Hold that bitch for ransom (Hold that bitch for ransom)',
      'I just wanna smoke it',
      'Take it out the baggies (Take it out the baggies), yeah',
      "I'ma go get me a brand new Bentley",
      "I'ma cruise it around the city",
      "Shoot in the crowd and then I'ma hit it (Shoot in the crowd)",
      "And you know my niggas wit' it",
      'I was thе one that put you on skinnies (I was the onе)',
      "And I count some money gettin' it",
      "I was just tellin' you (Hey), and I was just tellin' you, tellin' you",
      "I was just rollin' and waitin' my time (Yeah)",
      "I was in New York with a bad bitch like I'm a Giant (Woo)",
      "All them bitches bad, bring 'em to the back, you all on diamonds",
      "Givin' the bitch the dick, it's crack all on dimes (Yeah)",
      'Yeah, yeah, roll my blunt bitch, yeah, yeah (Yeah)',
      'And my necklace cost a couple squares, yeah (Swoo)',
      "And if you ain't a tire then you know you ain't gettin' spared, yeah",
      "I ain't tryna sound tough, I like her bad, yeah",
      "Gettin' slurped up my motion (Oh)",
      'Put it on her face like lotion',
      'Disappear, hokey pokey (Yeah)',
      "I was just livin' with some roaches (Yeah)",
      'Now I got a house full of groceries (Yeah)',
      'Now I got a house full of oceans (Yeah)',
      'And I got a pool on the inside (So what?)',
      'Yeah, I got a house with a ocean (Yeah)',
      'Run up, shut up (Yeah)',
      'Nigga try to run up, shut up (Shut up)',
      'Ayy, hold up, bet up',
      'Shut up, hold up, bet up',
      "Ridin' with the cannon, fuck 'round get wet up (Yeah)",
      'Pocket full of hunduns (Ayy, ayy)',
      'Shut up, catch up',
      'Vacuum seal the plastic (Vacuum seal the plastic)',
      "Shippin' and handlin' it (Yeah)",
      'Ship it off and stamp it (Ship it off)',
      'All my bitches ratchet (All my bitches ratchet)',
      'My car titanium',
      'Hold that bitch for ransom (Hold that bitch for ransom)',
      'I just wanna smoke it',
      'Take it out the baggies (Take it out the baggies), yeah',
      "I'ma go get me a brand new Bentley",
      "I'ma cruise it around the city",
      "Shoot in the crowd and then I'ma hit it (Shoot in the crowd)",
      "And you know my niggas wit' it",
      'I was the one that put you on skinnies (I was the one)',
      "And I count some money gettin' it",
      "I was just tellin' you (Hey), and I was just tellin' you, tellin' you",
      "I'ma gon' get some peso-so's",
      "I'm with some zoe-zoe-zoes",
      'Left wrist, right wrist froze, froze',
      "Left ear, right ear, ro', rose",
      'Catch up, you need some more, sure, sure',
      'Versace robe warm and cozy',
      "And we big time high-rollin', yeah",
      'Cop a Rollie, Rollie, Rollie like a roly-poly',
      "I'll fuck around and throw a hundred racks at ___",
      'Fuck around throw a lighter up at Follies, yeah',
      "I'm at Magic Monday with my shawty, yeah (With my shawty)",
      'Tell a hoe to pick her a bag',
      'Motherfuck the size of that bag',
      "G flyin' 'round, we classy",
      "Got a FN and it's plastic",
      "These pussy niggas wildin', these pussy niggas backstabbin'",
      "My nigga goin' brazy, my nigga big B, need a bandage",
      'Vacuum seal the plastic',
      "Shippin' and handlin' it",
      'Ship it off and stamp it (Ship it off)',
      'All my bitches ratchet (All my bitches hood, yeah)',
      'My car titanium (Titanium)',
      'Hold that bitch for ransom (Black card)',
      'I just wanna smoke it',
      'Take it out the baggies, yeah',
      "I'ma go get me a brand new Bentley",
      "I'ma cruise it around the city",
      "Shoot in the crowd and then I'ma hit it",
      "And you know my niggas wit' it",
      'I was the one that put you on skinnies',
      "And I count some money gettin' it",
      "I was just tellin' you, and I was just tellin' you, tellin' you",
    ],
  },
  {
    id: '7219e5a3-b0fa-48c0-ac3d-9fa0b291823e',
    song: {
      artist_names: 'Ola Playa (Ft. Bloody Jay \u0026 Young Thug)',
      full_title: 'All Kinda Drugs by Ola Playa (Ft. Bloody Jay \u0026 Young Thug)',
      header_image_thumbnail_url: 'https://images.genius.com/dd7505016988c4e4bdec938e7d7f1edb.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/dd7505016988c4e4bdec938e7d7f1edb.500x500x1.jpg',
      id: 0,
      uuid: '3020584',
      path: '/Ola-playa-all-kinda-drugs-lyrics',
      release_date_for_display: 'March 10, 2014',
      song_art_image_thumbnail_url: 'https://images.genius.com/dd7505016988c4e4bdec938e7d7f1edb.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/dd7505016988c4e4bdec938e7d7f1edb.500x500x1.jpg',
      title: 'All Kinda Drugs',
      url: 'https://genius.com/Ola-playa-all-kinda-drugs-lyrics',
    },
    lyrics: [
      "I'm on all kinds of drugs",
      "Shawty won't show me love",
      "I'm on all kinds of drugs",
      'She seen me throw it down',
      "I'm on all kinds of drugs",
      "Lil' mama give it up",
      "I'm on all kinds of drugs",
      "Lil' mama give it up",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "She dont wanna screw up her lil' remi",
      "When I'm on them drugs I can't land I'm not Disney",
      'Big B cup thicker then honey where my biscuit',
      'Look just like a star when they see me they make their wishes',
      "Hi I'm Bloody Jay I'm an addict",
      'Molly, lean, weed, yes I got to have it',
      'Ride and geek with Mondo we been at it all weekend',
      "We keep going up, up, up, can't sleep",
      'Say up, up, up',
      "I'm on all kinds of drugs",
      "Shawty won't show me love",
      "I'm on all kinds of drugs",
      'She seen me throw it down',
      "I'm on all kinds of drugs",
      'Lil mama give it up',
      "I'm on all kinds of drugs",
      'Lil mama give it up',
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "She dont wanna screw up her lil' remi",
      "When I'm on them drugs I can't land I'm not Disney",
      'Big B cup thicker then honey where my biscuit',
      'Look just like a star when they see me they make their wishes',
      "Hi I'm Bloody Jay I'm an addict",
      'Molly lean weed yes I got to have it',
      'Ride and geek with Mondo we been at it all weekend',
      "We keep going up, up, up, can't sleep",
      'Say up, up, up',
      "I'm on all kinds of drugs",
      "Shawty won't show me love",
      "I'm on all kinds of drugs",
      'She seen me throw it down',
      "I'm on all kinds of drugs",
      "Lil' mama give it up",
      "I'm on all kinds of drugs",
      "Lil' mama give it up",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
      "I'm on all kinds of drugs",
    ],
  },
  {
    id: '91e26cfa-9647-4594-8d0b-7a3569c3942d',
    song: {
      artist_names: 'Future \u0026 Young Thug',
      full_title: "Keep Goin' by Future \u0026 Young Thug",
      header_image_thumbnail_url: 'https://images.genius.com/895952634c3c5404e398ea2bed3fef3f.300x300x1.jpg',
      header_image_url: 'https://images.genius.com/895952634c3c5404e398ea2bed3fef3f.1000x1000x1.jpg',
      id: 0,
      uuid: '9316326',
      path: '/Future-and-young-thug-keep-goin-lyrics',
      release_date_for_display: '',
      song_art_image_thumbnail_url: 'https://images.genius.com/895952634c3c5404e398ea2bed3fef3f.300x300x1.jpg',
      song_art_image_url: 'https://images.genius.com/895952634c3c5404e398ea2bed3fef3f.1000x1000x1.jpg',
      title: 'Keep Goin’',
      url: 'https://genius.com/Future-and-young-thug-keep-goin-lyrics',
    },
    lyrics: [
      'Ooh, ooh, ooh',
      'Ooh, ooh, ooh',
      "Changin' gods (Ooh, ooh, ooh)",
      'Angel diamonds (Ooh, ooh, ooh)',
      'Protect me from the evil (Ooh, ooh, ooh)',
      'Angel diamonds (Ooh, ooh, ooh)',
      'Protect me from the evil (Ooh, ooh, ooh)',
      'Break: Future',
      'Ooh, ooh',
      'Ooh, ooh',
      'Ooh, ooh',
      'Ooh, ooh',
      'Who ever said love would die?',
      'One sentence, one million lives (Yeah, yeah, yeah)',
      "I'ma need turning around, and not a ___ would cry",
      '(Yeah, yeah, yeah, ooh, ooh)',
      'Keep my ___, my palms',
      'Feel free to wear my chores (Ooh, ooh)',
      'You never rung right on (Ooh, ooh)',
      "You never write at all, but keep goin' (Ooh, ooh, yeah, yeah)",
      'Break: Young Thug',
      "Keep goin', Keep goin'",
      "Keep goin', Keep goin' (Ooh, ooh)",
      'Yeah, yeah yeah',
      'Yeah, yeah yeah',
      'Yeah, yеah yeah',
      'Yeah',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
      'Ooh, ooh, ooh, ooh',
    ],
  },
];
