name: Pipeline
run-name: ${{ github.event.head_commit.message }}
on: [push]

env:
  STAGE: main
  REGION: us-east-1

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install project
        run: npm ci --silent
      - name: Build
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: Serverless Deploy
        run: npx serverless deploy --stage $STAGE --region $REGION --verbose